Repository hibernate/hibernate-reactive, pull requests merged in 2021-02, with the labels that each got.

#548 [#398] Update javadoc
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveProviderChecker.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/impl/ReactiveServiceInitiators.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJtaPlatformInitiator.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveMarkerServiceInitiator.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveMarkerServiceSingleton.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactivePersisterClassResolver.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactivePersisterClassResolverInitiator.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveQueryTranslatorFactory.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveQueryTranslatorFactoryInitiator.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveSessionFactoryBuilderInitiator.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/ReactiveSessionFactoryBuilderService.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryTranslatorImpl.java
Labels: documentation

#594 smoke test for @DynamicInsert @DynamicUpdate
  hibernate-reactive-core/src/test/java/org/hibernate/reactive/DynamicUpdateTest.java
Labels: testing

#595 smoke test for @Formula
  hibernate-reactive-core/src/test/java/org/hibernate/reactive/DynamicUpdateTest.java
  hibernate-reactive-core/src/test/java/org/hibernate/reactive/FormulaTest.java
Labels: testing

#605 improving hi/lo id generation
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/BlockingIdentifierGenerator.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/SequenceReactiveIdentifierGenerator.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/TableReactiveIdentifierGenerator.java
Labels: enhancement

#444 overload createNativeQuery() to accept query spaces
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/common/AffectedEntities.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyQueryImpl.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveQuery.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveNativeQueryImpl.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveQueryImpl.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageQueryImpl.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java
  hibernate-reactive-core/src/test/java/org/hibernate/reactive/QueryTest.java
  hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveSessionTest.java
  hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveStatelessSessionTest.java
Labels: enhancement

#618 add StatelessSession.fetch()
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveLoader.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/collection/impl/ReactiveCollectionLoader.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinyStatelessSessionImpl.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveStatelessSession.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/SessionUtil.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/Stage.java
  hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageStatelessSessionImpl.java
  hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyManyToOneAssociationTest.java
  hibernate-reactive-core/src/test/java/org/hibernate/reactive/LazyOneToManyAssociationWithFetchTest.java
Labels: enhancement
