Repository hibernate/hibernate-reactive, pull requests merged in 2025-05, with the labels that each got.

#2250 Remove JReleaser config from the sources
  ci/release/Jenkinsfile
  jreleaser.yml
Labels: 3.0

#2252 Backport to 2.4 : Remove JReleaser config from the sources
  ci/release/Jenkinsfile
  jreleaser.yml
Labels: 2.4

#2255 Upgrade Hibernate ORM to 6.6.15.Final
  README.md
  gradle.properties
Labels: 2.4

#2273 Update version in JBang templates to 3.0.0.Final
  tooling/jbang/CockroachDBReactiveTest.java.qute
  tooling/jbang/Db2ReactiveTest.java.qute
  tooling/jbang/Example.java
  tooling/jbang/MariaDBReactiveTest.java.qute
  tooling/jbang/MySQLReactiveTest.java.qute
  tooling/jbang/PostgreSQLReactiveTest.java.qute
  tooling/jbang/ReactiveTest.java
Labels: example, dependencies

#2282 [3.0] Test HQL new operator with many-to-one
  hibernate-reactive-core/src/test/java/org/hibernate/reactive/HQLQueryTest.java
Labels: testing, 3.0

#2283 [2.4] Test HQL new operator with many-to-one
  hibernate-reactive-core/src/test/java/org/hibernate/reactive/HQLQueryTest.java
Labels: testing, 2.4
