Repository hibernate/hibernate-reactive, pull requests merged in 2025-06, with the labels that each got.

#2302 [3.0] Upgrade Hibernate ORM to 7.0.2.Final
  README.md
  gradle.properties
Labels: upgrade, 3.0

#2308 Switch to Maven Central publishing (main)
  ci/release/Jenkinsfile
  ci/snapshot-publish.Jenkinsfile
  publish.gradle
Labels: ci

#2306 [2.4] Switch to Maven Central publishing
  ci/release/Jenkinsfile
  ci/snapshot-publish.Jenkinsfile
  publish.gradle
Labels: ci, 2.4

#2312 [2.4] Add JDK 26-ea to the build
  .github/workflows/build.yml
Labels: build, ci, 2.4

#2311 [3.0] Add JDK 26-ea to the build
  .github/workflows/build.yml
Labels: build, ci, 3.0
